# Reference cask. The authoritative version is generated by GoReleaser and pushed
# to EnJulian/homebrew-shadowbox on each release; do not edit this copy by hand.
cask "shadowbox" do
  version "1.2.0"
  sha256 "REPLACED_BY_GORELEASER"

  on_arm do
    url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-arm64.tar.gz"
  end
  on_intel do
    url "https://github.com/EnJulian/shadowbox/releases/download/v#{version}/shadowbox-darwin-amd64.tar.gz"
  end

  name "Shadowbox"
  desc "Music acquisition CLI for YouTube and Bandcamp"
  homepage "https://github.com/EnJulian/shadowbox"

  depends_on formula: "ffmpeg"
  depends_on formula: "yt-dlp"

  binary "shadowbox"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/shadowbox"]
  end
end
