name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v0.1.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            executable_name: shadowbox
          - os: windows-latest
            platform: windows
            arch: x64
            executable_name: shadowbox.exe
          - os: macos-latest
            platform: macos
            arch: x64
            executable_name: shadowbox
          - os: macos-latest
            platform: macos
            arch: arm64
            executable_name: shadowbox

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg aria2

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ffmpeg aria2

    - name: Install system dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ffmpeg aria2 -y

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r setup/requirements.txt
        pip install pyinstaller
        
    - name: Verify dependencies
      run: |
        python -c "
        import yt_dlp; print('✅ yt_dlp')
        import mutagen; print('✅ mutagen') 
        import requests; print('✅ requests')
        import PIL; print('✅ PIL')
        import spotipy; print('✅ spotipy')
        print('All dependencies verified successfully')
        "

    - name: Build executable (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller shadowbox.spec
        
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller shadowbox.spec
        
    - name: Test executable
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ./dist/shadowbox.exe --help
        else
          ./dist/shadowbox --help
        fi

    - name: Create archive name
      id: archive
      shell: bash
      run: |
        if [ "${{ matrix.platform }}" = "macos" ] && [ "${{ matrix.arch }}" = "arm64" ]; then
          echo "name=shadowbox-${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT
        else
          echo "name=shadowbox-${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT
        fi

    - name: Create release archive (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        cd dist
        tar -czf ${{ steps.archive.outputs.name }}.tar.gz shadowbox
        
    - name: Create release archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        7z a ${{ steps.archive.outputs.name }}.zip shadowbox.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.archive.outputs.name }}
        path: |
          dist/${{ steps.archive.outputs.name }}.tar.gz
          dist/${{ steps.archive.outputs.name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -la artifacts/

    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Shadowbox ${{ steps.version.outputs.version }}
        body: |
          ## Shadowbox ${{ steps.version.outputs.version }}
          
          ### Downloads
          - **Linux (x64)**: `shadowbox-linux-x64.tar.gz`
          - **Windows (x64)**: `shadowbox-windows-x64.zip`
          - **macOS (Intel)**: `shadowbox-macos-x64.tar.gz`
          - **macOS (Apple Silicon)**: `shadowbox-macos-arm64.tar.gz`
          
          ### Installation
          1. Download the appropriate file for your platform
          2. Extract the archive
          3. Run the executable
          
          ### Requirements
          - FFmpeg (for audio processing)
          - aria2 (for faster downloads)
          
          ### Usage
          ```bash
          ./shadowbox "song name artist"
          ./shadowbox https://youtube.com/watch?v=...
          ```
          
          For more information, see the [README](https://github.com/lsnen/shadowbox/blob/main/README.md).
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/shadowbox-linux-x64/shadowbox-linux-x64.tar.gz
        asset_name: shadowbox-linux-x64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/shadowbox-windows-x64/shadowbox-windows-x64.zip
        asset_name: shadowbox-windows-x64.zip
        asset_content_type: application/zip

    - name: Upload macOS Intel Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/shadowbox-macos-x64/shadowbox-macos-x64.tar.gz
        asset_name: shadowbox-macos-x64.tar.gz
        asset_content_type: application/gzip

    - name: Upload macOS ARM Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/shadowbox-macos-arm64/shadowbox-macos-arm64.tar.gz
        asset_name: shadowbox-macos-arm64.tar.gz
        asset_content_type: application/gzip